name: weatherworkshop
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.2
  bloc: ^8.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^7.7.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  loggy: ^2.0.3
  pretty_dio_logger: ^1.2.0-beta-1
  rive: ^0.9.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  assets:
    - assets/
  uses-material-design: true
  generate: true
